import { getTenantDisplayId, type Payment, type Tenant } from "../../../../packages/models";

interface ReceiptDetails {
  payment: Payment;
  tenantName: string;
  tenantId?: string;
  propertyName?: string;
  buildingName?: string;
  roomNumber?: string;
}

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

export function generateReceiptNumber() {
  const datePart = new Date().toISOString().slice(0, 10).replaceAll("-", "");
  const randomPart = Math.random().toString(36).slice(2, 8).toUpperCase();

  return `PEMS-${datePart}-${randomPart}`;
}

export function getTenantReceiptName(tenant: Tenant | null | undefined) {
  if (!tenant) return "Tenant";

  return `${getTenantDisplayId(tenant)} - ${tenant.fullName}`;
}

export function downloadPaymentReceipt({
  payment,
  tenantName,
  tenantId,
  propertyName,
  buildingName,
  roomNumber,
}: ReceiptDetails) {
  const receiptNumber = payment.receiptNumber || "Receipt pending";
  const amount = `${payment.currency} ${Number(payment.amount || 0).toLocaleString()}`;
  const period =
    payment.periodCoveredFrom || payment.periodCoveredTo
      ? `${payment.periodCoveredFrom || "Start not set"} to ${payment.periodCoveredTo || "End not set"}`
      : "Not specified";

  const rows = [
    ["Receipt No.", receiptNumber],
    ["Tenant", tenantName],
    ["Tenant ID", tenantId || "Not provided"],
    ["Property", propertyName || "Not provided"],
    ["Building", buildingName || "Not provided"],
    ["Room", roomNumber || "Not provided"],
    ["Payment Date", payment.paymentDate],
    ["Purpose", payment.paymentPurpose.replaceAll("_", " ")],
    ["Method", payment.paymentMethod.replaceAll("_", " ")],
    ["Amount", amount],
    ["Period Covered", period],
    ["Reference", payment.referenceNumber || "Not provided"],
    ["Status", payment.paymentStatus || "confirmed"],
    ["Notes", payment.notes || "None"],
  ];

  const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(receiptNumber)}</title>
  <style>
    body { margin: 0; background: #f8fafc; color: #0f172a; font-family: Inter, Arial, sans-serif; }
    main { max-width: 760px; margin: 32px auto; background: #fff; border: 1px solid #e2e8f0; border-radius: 16px; overflow: hidden; }
    header { background: #020617; color: #fff; padding: 28px; }
    .brand { color: #f59e0b; font-size: 12px; font-weight: 800; letter-spacing: .2em; text-transform: uppercase; }
    h1 { margin: 10px 0 0; font-size: 30px; }
    .amount { margin-top: 12px; color: #bfdbfe; font-size: 20px; font-weight: 800; }
    section { padding: 28px; }
    dl { display: grid; grid-template-columns: 180px 1fr; gap: 0; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; }
    dt, dd { margin: 0; padding: 13px 16px; border-bottom: 1px solid #e2e8f0; }
    dt { background: #f8fafc; color: #64748b; font-weight: 700; }
    dd { font-weight: 800; text-transform: capitalize; }
    dt:last-of-type, dd:last-of-type { border-bottom: 0; }
    footer { padding: 0 28px 28px; color: #64748b; font-size: 13px; }
    @media print { body { background: #fff; } main { margin: 0; border: 0; } }
  </style>
</head>
<body>
  <main>
    <header>
      <div class="brand">PEMS Receipt</div>
      <h1>${escapeHtml(receiptNumber)}</h1>
      <div class="amount">${escapeHtml(amount)}</div>
    </header>
    <section>
      <dl>
        ${rows
          .map(
            ([label, value]) =>
              `<dt>${escapeHtml(label)}</dt><dd>${escapeHtml(String(value))}</dd>`
          )
          .join("")}
      </dl>
    </section>
    <footer>
      This receipt was generated by PEMS after payment confirmation. Keep this copy for your records.
    </footer>
  </main>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = `${receiptNumber}.html`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}