export const COLLECTIONS = {
  SYSTEM: "system",
  USERS: "users",
  TENANT_LINK_REQUESTS: "tenantLinkRequests",
  PROPERTIES: "properties",
  BUILDINGS: "buildings",
  ROOMS: "rooms",
  TENANTS: "tenants",
  PAYMENTS: "payments",
  PAYMENT_REQUESTS: "paymentRequests",
  CONVERSATIONS: "conversations",
  MESSAGES: "messages",
  MAINTENANCE_REQUESTS: "maintenanceRequests",
  NOTIFICATIONS: "notifications",
  USER_SETTINGS: "userSettings",
  CARETAKERS: "caretakers",
  UTILITY_BILLS: "utilityBills",
  TENANCY_AGREEMENTS: "tenancyAgreements",
  RENT_SCHEDULES: "rentSchedules",
} as const;
